### ISSUE TITLE
sinto bam filement  returning a empty fragment filement

### ISSUE THREAD

**Issue by qiuqin-wu** [timoast/sinto#25]
Hi, Dr. Tim,
Hope this email finds you well!
I am using the tool sinto to create a scATAC-seq fragments file from the BAM file.
However, I came across an issue, that is, my output file is empty, which means there's nothing in it. Below is my screenshot of how to use the sinto tool. Could you please tell me whether I make a mistake and how to solve it?

#!/bin/bash
#SBATCH --partition=Orion
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --mem=64GB
#SBATCH --ntasks-per-node=1 
    
cd /scratch/qmei/wqq/mouse-TF/

export PATH=/users/qmei/anaconda3/bin/:$PATH

sinto fragments -b  Cerebellum_62216.bam  -f  Cerebellum_62216fragments.bed

**Comment by timoast** [comment]
Can you show the first few lines of your bam file?

**Comment by qiuqin-wu** [comment]
Below is my bam filement :http://krishna.gs.washington.edu/content/members/mouse_ATAC_atlas_website/bams/BoneMarrow_62016.bam















At 2020-12-06 00:28:31, "Tim Stuart" <notifications@github.com> wrote:

Can you show the first few lines of your bam file?

**Comment by timoast** [comment]
It looks like the cell barcode is stored in the read name in that bam file, rather than a "CB" read tag. See the documentation for [`fragments`](https://timoast.github.io/sinto/basic_usage.html#create-scatac-seq-fragments-file): the default is to look for a read tag named CB storing the cell barcode information. Use the `--barcode_regex` option to extract the cell barcode from the read name
