### ISSUE TITLE
Why collapsing reads across cell barcode?

### ISSUE THREAD

**Issue by hukai916** [timoast/sinto#36]
Hi developers, 

When extracting fragments from bam files, sinto would collapse fragments that share the exact same chr start and end coordinates across all cell barcode according to the documentation. Can you please justify this? Is there a reason why different cells can't harbor exactly the same fragments?

**Comment by timoast** [comment]
This was to mirror what was done by cellranger-atac v1

Cellranger has recently been updated to collapse fragments within a cell rather than across all cells, and we could similarly update sinto to do the same.

I don't have a whole lot of time to work on this right now, so I'd welcome a PR if anyone would like to contribute

**Comment by hukai916** [comment]
I see, thx.

**Comment by timoast** [comment]
Hi @hukai916, I've now added an option to only collapse duplicates that share the same coordinates and cell barcode (parameter `--collapse_within` in 0.7.6)

**Comment by hukai916** [comment]
Great, thank you!
