### ISSUE TITLE
Error running filterbarcodes

### ISSUE THREAD

**Issue by DrDrLitte** [timoast/sinto#6]
Good morning! I am using the filterbarcodes function to subset a bam to generate a psuedobulk bam file for further processing. When using the filterbarcodes function I came across two things:

1. Is the -o output part of the parameters required? The error:
 "sinto: error: unrecognized arguments: -o ./ " occurs.

2. If the -o parameter is left out the program will run generate two subfiles with the correct A_xx titles about 2-3g in size and exits with the following error leaving the two subfiles in place:

  "File "/risapps/rhel7/python/3.7.3/lib/python3.7/site-packages/sinto/filterbarcodes.py", line 55, in mergeAll
    raise Exception("samtools merge failed, temp files not deleted")
Exception: samtools merge failed, temp files not deleted"

What typically leads to this error? 

Thanks for your help!

**Comment by timoast** [comment]
I released a new version  yesterday that removes the `-o` parameter. You can find the documentation here: https://timoast.github.io/sinto/basic_usage.html#filter-cell-barcodes-from-bam-file

It seems like there's an error running the final merge. Since it doesn't delete the temporary files if the merge fails you can run `samtools merge` yourself and see if it works.

For example:

```
samtools merge output.bam <insert list of files>
```

If this command fails then the issue is with samtools rather than sinto

**Comment by DrDrLitte** [comment]
Updating samtools solved the issue, thanks timoast. Thanks for responding so fast and being so helpful!
